version: "3"
services:
    valkey:
        image: valkey/valkey:latest
        restart: unless-stopped
        ports:
          - "6379:6379"
        entrypoint: ['valkey-server']
        command: ['--save', '60', '1', '--loglevel', 'warning']
        volumes: 
            - ${HOME}/data/db/valkey:/data
        logging:
            options:
                max-size: "100k"
                max-file: "3"
